<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                //Variables para asignar el contenido de la descripcion del producto
                try {
                    $contentVisible =  substr($html, 0, 151);
                    $contentHidden = substr($html, 151);
                } catch (\Throwable $th) {
                    $th->getMessage();
                }
                
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                    aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                    <p>
                        <span><?=$contentVisible?><span id="points">...</span></span>
                    </p>
                    <div>
                        <span id="moreText" class="more-text"><?=$contentHidden?></span>
                        <span class="show-more" onclick="toggleText()" id="textBtn">LEER MAS</span>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
