<?php
/**
 *  @var Template $block
 *  @var BlogViewModel $viewModel
*/
use Magento\Framework\View\Element\Template;
use OmniPro\Blog\ViewModel\BlogViewModel;

$viewModel = $block->getData('view_model_items');
$collection = $viewModel->getBlogCollection();
$collection = array_reverse($collection);
    foreach ($collection as $post): ?>
       <div class="card mw-75 mt-3 border border-dark">
            <?php if($post["post_img"]!=null): ?>
                <img class="card-img-left p-2" src="<?='https://app.prueba-magento.test/pub/media/'.$post["post_img"]?>" alt="Imagen" width="200px">
            <?php endif; ?>
            <div class="card-body">
                <h5 class="card-title"><?=$post["post_title"]?></h5>
                <p class="card-text"><?=$post["post_content"]?></p>
                <p class="card-text"><?=substr($post["created_at"],0,10)?></p>
            </div>
        </div>
    <?php endforeach;
?>
